using Raven.CodeAnalysis.Diagnostics;
using Raven.CodeAnalysis.Text;

namespace Raven.CodeAnalysis.Tests.Workspaces;

public sealed class GeneratedFileRecognitionTests
{
    [Fact]
    public void EditorConfigGeneratedCode_OverridesFileConventionsPerDocument()
    {
        var directory = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(directory);
        try
        {
            var authoredPath = Path.Combine(directory, "Authored.rvn");
            var generatedPath = Path.Combine(directory, "Generated.g.rvn");
            File.WriteAllText(Path.Combine(directory, ".editorconfig"), """
root = true

[*.rvn]
generated_code = true

[*.g.rvn]
generated_code = false
""");
            var options = EditorConfigDiagnosticOptions.ApplyOptions(
                new CompilationOptions(OutputKind.DynamicallyLinkedLibrary),
                directory,
                [authoredPath, generatedPath]);
            var trees = new[]
            {
                Raven.CodeAnalysis.Syntax.SyntaxTree.ParseText("class Authored {}", path: authoredPath),
                Raven.CodeAnalysis.Syntax.SyntaxTree.ParseText("class Generated {}", path: generatedPath)
            };
            var analyzer = new OptOutAnalyzer();

            analyzer.Analyze(Compilation.Create("Test", trees, options)).ToArray();

            analyzer.Calls.ShouldBe(1);
            options.GeneratedCodeOptions[authoredPath].ShouldBeTrue();
            options.GeneratedCodeOptions[generatedPath].ShouldBeFalse();
        }
        finally
        {
            Directory.Delete(directory, recursive: true);
        }
    }

    [Fact]
    public void EditorConfigGeneratedCode_NearestFileAndLaterSectionWin()
    {
        var directory = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("N"));
        var nested = Path.Combine(directory, "src");
        Directory.CreateDirectory(nested);
        try
        {
            var sourcePath = Path.Combine(nested, "Input.rvn");
            File.WriteAllText(Path.Combine(directory, ".editorconfig"), """
root = true

[*.rvn]
generated_code = true
""");
            File.WriteAllText(Path.Combine(nested, ".editorconfig"), """
[*.rvn]
generated_code = false

[Input.rvn]
generated_code = true
""");

            var options = EditorConfigDiagnosticOptions.ApplyOptions(
                new CompilationOptions(OutputKind.DynamicallyLinkedLibrary),
                directory,
                [sourcePath]);

            options.GeneratedCodeOptions[sourcePath].ShouldBeTrue();
            options.WithSpecificDiagnosticOption("AN9050", ReportDiagnostic.Error)
                .GeneratedCodeOptions[sourcePath].ShouldBeTrue();
        }
        finally
        {
            Directory.Delete(directory, recursive: true);
        }
    }

    [Theory]
    [InlineData("Input.g.rvn", "class C {}", true)]
    [InlineData("Input.g.i.rvn", "class C {}", true)]
    [InlineData("Input.generated.rvn", "class C {}", true)]
    [InlineData("Input.DESIGNER.RVN", "class C {}", true)]
    [InlineData("TemporaryGeneratedFile_123.rvn", "class C {}", true)]
    [InlineData("C:\\code\\Input.g.rvn", "class C {}", true)]
    [InlineData("Input.rvn", "// <auto-generated/>\nclass C {}", true)]
    [InlineData("Input.rvn", "\n/* license */\n/* <autogenerated> */\nclass C {}", true)]
    [InlineData("Input.rvn", "/// <auto-generated>\nclass C {}", true)]
    [InlineData("Input.rvn", "class C {} // <auto-generated>", false)]
    [InlineData("Input.rvn", "class C { // <auto-generated>\n }", false)]
    [InlineData("Input.rvn", "// generated by a person\nclass C {}", false)]
    [InlineData("Input.rvn", "// <AUTO-GENERATED>\nclass C {}", false)]
    [InlineData("generated/Input.rvn", "class C {}", false)]
    [InlineData("Input.g.rvn.backup", "class C {}", false)]
    [InlineData("generated.rvn", "class C {}", false)]
    public void GeneratedFileConventions_ControlAnalyzerCallbacks(string path, string source, bool generated)
    {
        var tree = Raven.CodeAnalysis.Syntax.SyntaxTree.ParseText(source, path: path);
        var analyzer = new OptOutAnalyzer();
        var compilation = Compilation.Create("Test", [tree]);
        analyzer.Analyze(compilation).Count().ShouldBe(generated ? 0 : 1);
        analyzer.Calls.ShouldBe(generated ? 0 : 1);
    }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public void AddingAndRemovingGeneratedHeader_RefreshesDiagnostics(bool documentLane)
    {
        var workspace = new AdhocWorkspace();
        var solution = workspace.CurrentSolution.AddProject("HeaderEdits");
        var projectId = solution.Projects.Single().Id;
        var documentId = DocumentId.CreateNew(projectId);
        solution = solution.AddDocument(documentId, "Input.rvn", SourceText.From("class C {}"), "/Input.rvn")
            .AddAnalyzerReference(projectId, new AnalyzerReference(new OptOutAnalyzer()));
        workspace.TryApplyChanges(solution).ShouldBeTrue();

        int Analyze() => (documentLane
            ? workspace.GetDocumentAnalyzerDiagnostics(projectId, documentId)
            : workspace.GetDiagnostics(projectId)).Count(diagnostic => diagnostic.Id == "AN9050");

        Analyze().ShouldBe(1);
        workspace.TryApplyChanges(workspace.CurrentSolution.WithDocumentText(documentId,
            SourceText.From("// <auto-generated/>\nclass C {}"))).ShouldBeTrue();
        Analyze().ShouldBe(0);
        workspace.TryApplyChanges(workspace.CurrentSolution.WithDocumentText(documentId,
            SourceText.From("class C {}"))).ShouldBeTrue();
        Analyze().ShouldBe(1);
    }

    [Theory]
    [InlineData("Input.g.rvn", "class C {}", false)]
    [InlineData("Input.g.rvn", "class C {}", true)]
    [InlineData("Input.rvn", "// <auto-generated/>\nclass C {}", false)]
    [InlineData("Input.rvn", "// <auto-generated/>\nclass C {}", true)]
    public void GeneratedConventions_FilterDiagnosticsFromCompilationCallbacks(string path, string source, bool report)
    {
        var tree = Raven.CodeAnalysis.Syntax.SyntaxTree.ParseText(source, path: path);
        var compilation = Compilation.Create("Test", [tree]);
        var diagnostics = new ReportingAnalyzer(report).Analyze(compilation).ToArray();
        diagnostics.Length.ShouldBe(report ? 2 : 1);
        diagnostics.ShouldContain(diagnostic => diagnostic.Location == Location.None);
    }

    private sealed class ReportingAnalyzer(bool report) : DiagnosticAnalyzer
    {
        private static readonly DiagnosticDescriptor Rule = DiagnosticDescriptor.Create(
            "AN9051", "Reporting", null, "", "Reporting", "Testing", DiagnosticSeverity.Warning);
        public override void Initialize(AnalysisContext context)
        {
            context.ConfigureGeneratedCodeAnalysis(report ? GeneratedCodeAnalysisFlags.ReportDiagnostics : GeneratedCodeAnalysisFlags.None);
            context.RegisterCompilationAction(action =>
            {
                action.ReportDiagnostic(Diagnostic.Create(Rule,
                    Location.Create(action.Compilation.SyntaxTrees.Single(), new TextSpan(0, 1))));
                action.ReportDiagnostic(Diagnostic.Create(Rule, Location.None));
            });
        }
    }

    private sealed class OptOutAnalyzer : DiagnosticAnalyzer
    {
        public int Calls { get; private set; }
        private static readonly DiagnosticDescriptor Rule = DiagnosticDescriptor.Create(
            "AN9050", "Header", null, "", "Header", "Testing", DiagnosticSeverity.Warning);
        public override void Initialize(AnalysisContext context)
        {
            context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
            context.RegisterSyntaxTreeAction(action =>
            {
                Calls++;
                action.ReportDiagnostic(Diagnostic.Create(Rule, Location.None));
            });
        }
    }
}
