namespace Raven.CodeAnalysis.Syntax;

public partial class SyntaxTree
{
    // Cache classification per immutable tree; source-generator provenance remains separate.
    private int _generatedCodeClassification;

    internal bool IsGeneratedCode
    {
        get
        {
            var classification = Volatile.Read(ref _generatedCodeClassification);
            if (classification == 0)
            {
                classification = IsGenerated || HasGeneratedFileName() || HasGeneratedHeader() ? 2 : 1;
                Volatile.Write(ref _generatedCodeClassification, classification);
            }
            return classification == 2;
        }
    }

    private bool HasGeneratedFileName()
    {
        var fileName = Path.GetFileName(FilePath.Replace('\\', '/'));
        if (fileName.StartsWith("TemporaryGeneratedFile_", StringComparison.OrdinalIgnoreCase))
            return true;

        var stem = Path.GetFileNameWithoutExtension(fileName);
        return stem.EndsWith(".g", StringComparison.OrdinalIgnoreCase) ||
            stem.EndsWith(".g.i", StringComparison.OrdinalIgnoreCase) ||
            stem.EndsWith(".generated", StringComparison.OrdinalIgnoreCase) ||
            stem.EndsWith(".designer", StringComparison.OrdinalIgnoreCase);
    }

    private bool HasGeneratedHeader()
    {
        foreach (var trivia in GetRoot().GetLeadingTrivia())
        {
            if (trivia.Kind is not (SyntaxKind.SingleLineCommentTrivia or
                SyntaxKind.MultiLineCommentTrivia or SyntaxKind.DocumentationCommentTrivia))
                continue;

            var text = trivia.ToString();
            if (text.Contains("<auto-generated", StringComparison.Ordinal) ||
                text.Contains("<autogenerated", StringComparison.Ordinal))
                return true;
        }
        return false;
    }
}
